Rename en/decrypt.sh to en/decrypt

diff --git a/encrypt b/encrypt
--- a/encrypt
+++ b/encrypt
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2317
 
-[[ "$1" == "decrypt.sh" ]] && shift
+[[ "$1" == "encrypt" ]] && shift
 
-if [[ ! -f "decrypt.sh" ]]; then
-    echo "ERROR: decrypt.sh can only be invoked in its own directory (current working directory: $(pwd))" >&2
+if [[ ! -f "./encrypt" ]]; then
+    echo "ERROR: encrypt can only be invoked in its own directory (current working directory: $(pwd))" >&2
     return 1 2>/dev/null || exit 1
 elif [[ ! -f ".gpg2f/scripts/gpg2f.sh" ]]; then
     echo "ERROR: $(pwd)/.gpg2f/scripts/gpg2f.sh does not exist" >&2
     return 1 2>/dev/null || exit 1
-elif ! . .gpg2f/scripts/gpg2f.sh decrypt "$@"; then
+elif ! . .gpg2f/scripts/gpg2f.sh encrypt "$@"; then
     return 1 2>/dev/null || exit 1
 fi
